server:
  port: 8080

HOST_IP: 127.0.0.1
GB_ENABLE: false
interface:
externIp:
NMS_enable: false
map_provider: gaode
mobicaster_url: http://127.0.0.1:8082
smh:
  base_url: http://${HOST_IP}:9001

gateway:
  base_url: http://${HOST_IP}:61616

transcoding:
  base_url: http://${HOST_IP}:9004

mediakit:
  base_url: http://${HOST_IP}:8081
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc   # 这个值可以在mediakit配置文件中进行设置

GB:
  base_url: http://${HOST_IP}:9005

source:
  interface: ${interface}

foldback:
  port: ${FOLDBACK_PORT:9000}

minio:
  addr: ${HOST_IP}:9002
  accessKey: xFkEokGRxAlwIs4Vw5cO
  secretKey: jaz4FlvCDDKvbBuQYJ9NIohMUlRDsT09F1PZH6KB
